const DATA_SOURCE = 'DATA_SOURCE'
const REPOSITORY = {
    PATIENTS : 'PATIENT_REPOSITORY',
    CONSUPMTION_SHEETS : 'CONSUPMTION_SHEET_REPOSITORY',
    CONSUMPTION_DETAILS : 'CONSUMPTION_DETAIL_REPOSITORY',
    PRODUCTS : 'PRODUCT_REPOSITORY',
    ROOMS : 'ROOM_REPOSITORY',
    USERS : 'USER_REPOSITORY',
    STAFF : 'STAFF_REPOSITORY',
}
export {DATA_SOURCE, REPOSITORY}