import { MigrationInterface, QueryRunner } from "typeorm";

export class MYSQLCOMPATMigr1683444208804 implements MigrationInterface {
    name = 'MYSQLCOMPATMigr1683444208804'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP FOREIGN KEY \`FK_CONSUMPTION_SHEET_PATIENT_ID\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP FOREIGN KEY \`FK_CONSUMPTION_SHEET_ROOM_ID\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_staff_user_id\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`product\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`room\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`patient\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`consumption_sheet\``);
        await queryRunner.query(`DROP INDEX \`UQ_ce6fe55c4903708850ba89a967a\` ON \`consumption_sheet\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`UQ_cace4a159ff9f2512dd42373760\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`UQ_e12875dfb3b1d92d7d7c5377e22\` ON \`user\``);
        await queryRunner.query(`DROP INDEX \`id\` ON \`staff\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_baeea2c4c8215d93bd25467921a\``);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`patient\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`date_of_birth\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`patient\` CHANGE \`active\` \`active\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_0fc93b6c16d66d8cac7580e6c61\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`patient_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`patient_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD UNIQUE INDEX \`IDX_ce6fe55c4903708850ba89a967\` (\`patient_id\`)`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`room_id\` int UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`discharge_date\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`discharge_date\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`admission_date\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`admission_date\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_4f79974192afdc1fb9c10e41233\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`email\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD UNIQUE INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`role\` \`role\` enum ('1', '2', '10') NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_c6769cc6c8f0fa486979d64d2f1\``);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`id\` int NOT NULL PRIMARY KEY AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`date_of_birth\` datetime NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`user_id\` int UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`deleted_at\` datetime(6) NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`consumption_sheet_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`consumption_sheet_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`product_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`product_id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`staff_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`staff_id\` int NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`user_id\` int NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_ce6fe55c4903708850ba89a967\` ON \`consumption_sheet\` (\`patient_id\`)`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD CONSTRAINT \`FK_ce6fe55c4903708850ba89a967a\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patient\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD CONSTRAINT \`FK_6fdf8e1a7854a8cbaff418f4a9e\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_cec9365d9fc3a3409158b645f2e\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_0fc93b6c16d66d8cac7580e6c61\` FOREIGN KEY (\`consumption_sheet_id\`) REFERENCES \`consumption_sheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_baeea2c4c8215d93bd25467921a\` FOREIGN KEY (\`product_id\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_c6769cc6c8f0fa486979d64d2f1\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_4f79974192afdc1fb9c10e41233\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_4f79974192afdc1fb9c10e41233\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_c6769cc6c8f0fa486979d64d2f1\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_baeea2c4c8215d93bd25467921a\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP FOREIGN KEY \`FK_0fc93b6c16d66d8cac7580e6c61\``);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP FOREIGN KEY \`FK_cec9365d9fc3a3409158b645f2e\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP FOREIGN KEY \`FK_6fdf8e1a7854a8cbaff418f4a9e\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP FOREIGN KEY \`FK_ce6fe55c4903708850ba89a967a\``);
        await queryRunner.query(`DROP INDEX \`REL_ce6fe55c4903708850ba89a967\` ON \`consumption_sheet\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`user_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`staff_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`staff_id\` bigint UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`product_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`product_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`consumption_sheet_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`consumption_sheet_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`user_id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`user_id\` bigint UNSIGNED NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`date_of_birth\` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`staff\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`staff\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_c6769cc6c8f0fa486979d64d2f1\` FOREIGN KEY (\`staff_id\`) REFERENCES \`staff\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`role\` \`role\` enum ('1', '2', '3') NOT NULL DEFAULT '1'`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP INDEX \`IDX_e12875dfb3b1d92d7d7c5377e2\``);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`email\`, \`id\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` int NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`user\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`user\` DROP PRIMARY KEY`);
        await queryRunner.query(`ALTER TABLE \`user\` ADD PRIMARY KEY (\`id\`, \`email\`)`);
        await queryRunner.query(`ALTER TABLE \`user\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_4f79974192afdc1fb9c10e41233\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`admission_date\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`admission_date\` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`discharge_date\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`discharge_date\` timestamp NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`room_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`room_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP INDEX \`IDX_ce6fe55c4903708850ba89a967\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`patient_id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`patient_id\` bigint UNSIGNED NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_0fc93b6c16d66d8cac7580e6c61\` FOREIGN KEY (\`consumption_sheet_id\`) REFERENCES \`consumption_sheet\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`patient\` CHANGE \`active\` \`active\` tinyint(1) NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`date_of_birth\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`date_of_birth\` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00'`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`patient\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`patient\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`patient\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`room\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`room\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`room\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`room\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product\` DROP COLUMN \`id\``);
        await queryRunner.query(`ALTER TABLE \`product\` ADD \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`product\` ADD PRIMARY KEY (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`product\` CHANGE \`id\` \`id\` bigint UNSIGNED NOT NULL AUTO_INCREMENT`);
        await queryRunner.query(`ALTER TABLE \`consumption_detail\` ADD CONSTRAINT \`FK_baeea2c4c8215d93bd25467921a\` FOREIGN KEY (\`product_id\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`deleted_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`deleted_at\` timestamp(0) NULL`);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`updated_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`updated_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` DROP COLUMN \`created_at\``);
        await queryRunner.query(`ALTER TABLE \`product_sat_category\` ADD \`created_at\` timestamp(0) NOT NULL DEFAULT CURRENT_TIMESTAMP()`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`staff\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_e12875dfb3b1d92d7d7c5377e22\` ON \`user\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_cace4a159ff9f2512dd42373760\` ON \`user\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`user\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`UQ_ce6fe55c4903708850ba89a967a\` ON \`consumption_sheet\` (\`patient_id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`consumption_sheet\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`patient\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`room\` (\`id\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`id\` ON \`product\` (\`id\`)`);
        await queryRunner.query(`ALTER TABLE \`staff\` ADD CONSTRAINT \`FK_staff_user_id\` FOREIGN KEY (\`user_id\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD CONSTRAINT \`FK_CONSUMPTION_SHEET_ROOM_ID\` FOREIGN KEY (\`room_id\`) REFERENCES \`room\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`consumption_sheet\` ADD CONSTRAINT \`FK_CONSUMPTION_SHEET_PATIENT_ID\` FOREIGN KEY (\`patient_id\`) REFERENCES \`patient\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

}
